### ISSUE TITLE
Cannot use object of type Staudenmeir\LaravelCte\Connections\MySqlConnection as array

### ISSUE THREAD

**Issue by zabavnikov** [staudenmeir/laravel-cte#45]
When trying to register, this code gives the error `Cannot use object of type Staudenmeir\\LaravelCte\\Connections\\MySqlConnection as array`, but if you remove the transaction, the code will work as it should.

```php
final class Register
{
    private User $user;

    /**
     * @throws ValidationException
     */
    public function __invoke($rootValue, array $args): User
    {
        Validator::make($args['input'], [
            'username' => ['required', 'regex:/^[a-zA-Z0-9]+$/u', 'min:2', 'max:16', 'unique:users'],
            'email' => ['required', 'email', 'max:35', 'unique:users'],
            'password' => ['required', 'min:8'],
            'password_confirmation' => ['required', 'same:password'],
        ])->validate();

        DB::transaction(function ($args) {
            $this->user = User::create([
                'username' => $args['input']['username'],
                'email' => $args['input']['email'],
                'password' => Hash::make($args['input']['password']),
            ]);

            if ($this->user->id === 1) {
                $this->user->update([
                    'role' => 'administrator',
                    'email_verified_at' => Carbon::now(),
                ]);
            } else {
                event(new Registered($this->user));
            }
        });

        return $this->user;
    }
}
```

**Comment by staudenmeir** [comment]
Hi @zabavnikov,
Please share the whole error with the stacktrace.

**Comment by zabavnikov** [comment]
> Hi @zabavnikov, Please share the whole error with the stacktrace.

```
[2023-04-09 10:31:17] local.ERROR: Cannot use object of type Staudenmeir\LaravelCte\Connections\MySqlConnection as array {"exception":"[object] (Error(code: 0): Cannot use object of type Staudenmeir\\LaravelCte\\Connections\\MySqlConnection as array at /var/www/html/app/Modules/Users/GraphQL/Mutations/Authentication/Register.php:31)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): app\\Modules\\Users\\GraphQL\\Mutations\\Authentication\\Register->app\\Modules\\Users\\GraphQL\\Mutations\\Authentication\\{closure}(Object(Staudenmeir\\LaravelCte\\Connections\\MySqlConnection))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\\Database\\Connection->transaction(Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#3 /var/www/html/app/Modules/Users/GraphQL/Mutations/Authentication/Register.php(29): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#4 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Values/FieldValue.php(193): app\\Modules\\Users\\GraphQL\\Mutations\\Authentication\\Register->__invoke(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(Nuwave\\Lighthouse\\Execution\\ResolveInfo))
#5 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(713): Nuwave\\Lighthouse\\Schema\\Values\\FieldValue->Nuwave\\Lighthouse\\Schema\\Values\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#6 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(633): GraphQL\\Executor\\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\\Type\\Definition\\FieldDefinition), Object(GraphQL\\Language\\AST\\FieldNode), Object(Closure), NULL, Object(GraphQL\\Type\\Definition\\ResolveInfo))
#7 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(544): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#8 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(945): GraphQL\\Executor\\ReferenceExecutor->GraphQL\\Executor\\{closure}(Array, 'register')
#9 [internal function]: GraphQL\\Executor\\ReferenceExecutor->GraphQL\\Executor\\{closure}(Array, 'register')
#10 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(937): array_reduce(Array, Object(Closure), Array)
#11 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(536): GraphQL\\Executor\\ReferenceExecutor->promiseReduce(Array, Object(Closure), Array)
#12 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(297): GraphQL\\Executor\\ReferenceExecutor->executeFieldsSerially(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#13 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(237): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#14 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Executor.php(163): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#15 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(157): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL)
#16 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(91): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL, Array)
#17 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(118): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL, Array)
#18 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(86): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery(Object(GraphQL\\Language\\AST\\DocumentNode), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL)
#19 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(212): Nuwave\\Lighthouse\\GraphQL->executeQueryString('mutation regist...', Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL)
#20 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(177): Nuwave\\Lighthouse\\GraphQL->executeOperation(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#21 /var/www/html/vendor/nuwave/lighthouse/src/Support/Utils.php(107): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}(Object(GraphQL\\Server\\OperationParams))
#22 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(173): Nuwave\\Lighthouse\\Support\\Utils::mapEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#23 /var/www/html/vendor/nuwave/lighthouse/src/Http/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Nuwave\\Lighthouse\\Http\\GraphQLController->__invoke(Object(Illuminate\\Http\\Request), Object(Nuwave\\Lighthouse\\GraphQL), Object(Illuminate\\Events\\Dispatcher), Object(Laragraph\\Utils\\RequestParser), Object(Nuwave\\Lighthouse\\Execution\\SingleResponse), Object(Nuwave\\Lighthouse\\Execution\\ContextFactory))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Http\\GraphQLController), '__invoke')
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/vendor/nuwave/lighthouse/src/Http/Middleware/AttemptAuthentication.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AttemptAuthentication->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/html/vendor/nuwave/lighthouse/src/Http/Middleware/AcceptJson.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AcceptJson->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/html/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#60 {main}
"} 
```
[laravel-2023-04-09.log](https://github.com/staudenmeir/laravel-cte/files/11185233/laravel-2023-04-09.log)

**Comment by zabavnikov** [comment]
```php
<?php

namespace App\Modules\Users\Models;

use App\Modules\Users\Notifications\ResetPasswordNotification;
use App\Modules\Users\Notifications\VerifyEmailNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use PHPOpenSourceSaver\JWTAuth\Contracts\JWTSubject;
use Staudenmeir\EloquentEagerLimitXLaravelAdjacencyList\Eloquent\HasEagerLimitAndRecursiveRelationships;
use NextApps\VerificationCode\VerificationCode;

class User extends Authenticatable implements JWTSubject, MustVerifyEmail
{
    use HasEagerLimitAndRecursiveRelationships;
    use HasFactory;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role',
        'email',
        'password',
        'username',
        'name',
        'avatar',
        'cover',
        'plus_purchased_before',
        'username_updated_at',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
    ];

    protected $rememberTokenName = false;

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'plus_purchased_before' => 'datetime',
        'username_updated_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier(): mixed
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims(): mixed
    {
        return [];
    }

    /**
     * Аватар пользователя.
     */
    public function getAvatarAttribute($value): string|null
    {
        if ($value) {
            $timestamp = $this->updated_at->timestamp;
            return Storage::url("$value?$timestamp");
        }

        return null;
    }

    /**
     * Аватар пользователя.
     */
    public function getCoverAttribute($value): string|null
    {
        if ($value) {
            $timestamp = $this->updated_at->timestamp;
            return Storage::url("$value?$timestamp");
        }

        return null;
    }


    protected function name(): Attribute
    {
        return Attribute::make(
            get: fn (string|null $value) => $value ?? $this->attributes['username'],
            set: function (string|null $value) {
                $value = trim(strip_tags($value));

                if (mb_strlen($value) === 0) {
                    return null;
                }

                return $value;
            },
        );
    }

    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification(): void
    {
        VerificationCode::send($this->email);
        // $this->notify(new VerifyEmailNotification());
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     *
     * @return void
     */
    public function sendPasswordResetNotification($token): void
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}
```

**Comment by staudenmeir** [comment]
>  at /var/www/html/app/Modules/Users/GraphQL/Mutations/Authentication/Register.php:31

Which is line 31 of `Register.php`?

**Comment by staudenmeir** [comment]
What Laravel version are you using?

**Comment by zabavnikov** [comment]
![image](https://user-images.githubusercontent.com/8766240/230772453-c77714fd-6b28-4256-88b7-3462bef22d11.png)
hmm very strange

Laravel 10

**Comment by zabavnikov** [comment]
I have removed the Has Eager Limit And Recursive Relationship trait from the user model, but I still get this error.

**Comment by staudenmeir** [comment]
Replace line 29 with this:

```php
DB::transaction(function () use ($args) {
```

**Comment by zabavnikov** [comment]
> Replace line 29 with this:
> 
> ```
> DB::transaction(function () use ($args) {
> ```

@staudenmeir ohh, because of my inattention, I wasted your time, I apologize. 😅😅😅
